use_frameworks!

platform :ios, '8.0'

target 'BlueTriangleSDK-iOS_Example' do
  pod 'BlueTriangleSDK-iOS', :path => '../'

  target 'BlueTriangleSDK-iOS_Tests' do
    inherit! :search_paths

    
  end
end
